syntax on

set nu
set cul

set ts=4 sw=4 et 
set expandtab
set autoindent
set fileencoding=utf-8
set nowrap

set incsearch
set hlsearch
set ignorecase
set smartcase

set laststatus=2
" set noshowmode

set nobackup
set nowritebackup
set noswapfile

set undodir=~/.vim/undodir
set undofile

set lazyredraw
set wildmenu
set showmatch 

set clipboard=unnamedplus

set background=dark
set timeoutlen=1000 ttimeoutlen=0

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'kien/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
call plug#end()

colorscheme Tomorrow-Night-Bright 
hi! Normal ctermbg=NONE guibg=NONE
hi! nonText ctermbg=NONE guibg=NONE

let mapleader = "\<Space>"

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>


